package com.example.softlearning_springboot.applicationcore.entity.orders.model;

public enum OrderStatus {
    CREATED, // SOLO SE HA CREADO EL ORDER, PENDIENTE DE CONFIRMATION
    CANCELLED, // ORDER CANCELADO
    CONFIRMED,  // CARRITO VALIDADO Y PAGADO
    FORTHCOMMING, // PAQUETE PREPARADO Y ALMACENADO PENDIENTE DE ENVIO
    DELIVERED, // ENVIO ENTREGADO AL TRANSPORTISTA CON DESTINO AL CLIENTE
    FINISHED // ENVIO ENTREGADO AL CLIENTE
}
