package com.example.softlearning_springboot.applicationcore.entity.sharedkernel.appservices.serializers;

public enum Serializers {
    JSON_CLIENT,
    JSON_SP_CLIENT,
    XML_CLIENT,
    XML_SP_CLIENT,
    JSON_BOOK,
    JSON_SP_BOOK,
    XML_BOOK,
    XML_SP_BOOK,
    JSON_ORDER,
    JSON_SP_ORDER,
    XML_ORDER,
    XML_SP_ORDER,
    JSON_COURSE,
    JSON_SP_COURSE,
    XML_COURSE,
    XML_SP_COURSE,
    JSON_EMPLOYEE,
    JSON_SP_EMPLOYEE,
    XML_EMPLOYEE,
    XML_SP_EMPLOYEE,
    JSON_PROVIDER,
    JSON_SP_PROVIDER,
    XML_PROVIDER,
    XML_SP_PROVIDER, 
    BOOK_JSON, 
    BOOK_XML,
}